const cfg=window.NIMU_CONFIG;
const configured=!cfg.SUPABASE_URL.includes("YOUR_")&&!cfg.SUPABASE_PUBLISHABLE_KEY.includes("YOUR_");
const supabase=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;
const $=id=>document.getElementById(id); const chat=$("chat"), input=$("input"), form=$("chatForm");
let history=[], signup=false, demo=!configured;

function add(role,text){const row=document.createElement("div");row.className="row "+role;const box=document.createElement("div");box.className="bubble";box.textContent=text;row.appendChild(box);if(role==="ai"){const tools=document.createElement("div");tools.className="tools";const b=document.createElement("button");b.textContent="🔊";b.title="Read aloud";b.onclick=()=>speak(text);tools.appendChild(b);row.appendChild(tools)}chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function typing(){const row=document.createElement("div");row.className="row ai";row.id="typing";row.innerHTML='<div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div>';chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function speak(t){if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.96;u.pitch=1.06;speechSynthesis.speak(u)}}
async function session(){if(!supabase)return null;const {data}=await supabase.auth.getSession();return data.session}
async function refresh(){const s=await session(); if(s){$("auth").style.display="none";$("userBadge").textContent=s.user.email; $("memoryStatus").textContent="Memory is on. Your conversations can follow you across sessions."; $("logout").style.display="block"; loadHistory()} else {$("auth").style.display="grid";$("userBadge").textContent="Guest";$("logout").style.display="none"}}
async function loadHistory(){const s=await session();if(!s)return;try{const r=await fetch("/.netlify/functions/history",{headers:{Authorization:"Bearer "+s.access_token}});const d=await r.json();if(d.messages?.length){document.querySelector(".hero")?.remove();d.messages.forEach(m=>{add(m.role==="assistant"?"ai":"user",m.content);history.push({role:m.role,content:m.content})})}}catch(e){console.warn(e)}}
$("loginTab").onclick=()=>{signup=false;$("loginTab").classList.add("active");$("signupTab").classList.remove("active");$("authSubmit").textContent="Log in"}
$("signupTab").onclick=()=>{signup=true;$("signupTab").classList.add("active");$("loginTab").classList.remove("active");$("authSubmit").textContent="Create account"}
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="";if(!supabase){demo=true;$("auth").style.display="none";return}const email=$("email").value,password=$("password").value;let res=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(res.error){$("authMsg").textContent=res.error.message;return}if(signup&&!res.data.session)$("authMsg").textContent="Check your email to confirm your account.";else refresh()}
$("demoBtn").onclick=()=>{$("auth").style.display="none";demo=true;$("memoryStatus").textContent="Guest mode: memory stays only in this browser session."}
$("logout").onclick=async()=>{if(supabase)await supabase.auth.signOut();location.reload()}
document.querySelectorAll(".chips button").forEach(b=>b.onclick=()=>{input.value=b.textContent.replace(/[✨💗😂]/g,"").trim();input.focus()});
form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;document.querySelector(".hero")?.remove();add("user",text);history.push({role:"user",content:text});input.value="";$("send").disabled=true;typing();
try{let headers={"Content-Type":"application/json"};const s=await session();if(s)headers.Authorization="Bearer "+s.access_token;const r=await fetch("/.netlify/functions/chat",{method:"POST",headers,body:JSON.stringify({messages:history.slice(-24),guest:!s})});const d=await r.json();$("typing")?.remove();if(!r.ok)throw Error(d.error||"Request failed");add("ai",d.reply);history.push({role:"assistant",content:d.reply})}catch(err){$("typing")?.remove();add("ai","I couldn't connect right now. Please check your setup.");console.error(err)}finally{$("send").disabled=false;input.focus()}};
$("mic").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Voice input is not supported in this browser.");return}const r=new SR();r.lang="bn-BD";r.interimResults=false;r.onresult=e=>{input.value=e.results[0][0].transcript;input.focus()};r.start()};
if(supabase)supabase.auth.onAuthStateChange(()=>refresh()); else refresh();