-- Run this in Supabase SQL Editor.
create table if not exists public.nimu_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);
alter table public.nimu_messages enable row level security;
create policy "Users can read own messages" on public.nimu_messages for select using (auth.uid() = user_id);
create index if not exists nimu_messages_user_created on public.nimu_messages(user_id, created_at);
