-- Security baseline for Nimu AI message storage.
-- The service-role key must NEVER be shipped to the browser.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Remove broad/legacy policies before creating the intended ones.
drop policy if exists "Users can read own messages" on public.messages;
drop policy if exists "Users can insert own messages" on public.messages;
drop policy if exists "Users can delete own messages" on public.messages;

-- Browser clients can read only their own messages.
create policy "Users can read own messages"
on public.messages
for select
to authenticated
using (auth.uid() = user_id);

-- Browser clients may insert only rows belonging to themselves.
-- The Netlify service-role client bypasses RLS and remains responsible for
-- server-side validation and authentication.
create policy "Users can insert own messages"
on public.messages
for insert
to authenticated
with check (auth.uid() = user_id);

-- Allow users to delete only their own history.
create policy "Users can delete own messages"
on public.messages
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists messages_user_id_created_at_idx
on public.messages (user_id, created_at);
